package by.htp.ex.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, GO_TO_LOGINATION_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_NEWS_LIST, GO_TO_VIEW_NEWS,

	DO_SIGN_IN, DO_SIGN_OUT, SAVE_NEWS, GO_TO_ADD_NEWS, DELETE_NEWS, GO_TO_CONFIRMATION_PAGE, GO_TO_EDIT_NEWS,
	
	NO_SUCH_FUNCTION, DO_REGISTRATION, UPDATE_NEWS, GO_TO_ERROR_PAGE, CHANGE_LOCALE
}
